### ISSUE TITLE
Semantics of boolean variables in ContraintGrammar class (cleanup branch)

### ISSUE THREAD

**Issue by muraliadithya** [eionblanc/mini-sygus#13]
Two tasks:
- Ensure that the evaluation function agrees with the interpretation of functions and boolean variables in the smt encoding pretty printer (currently it does not --- pretty printer has a catchall case whereas the evaluation function raises an exception)
- Reduce the number of boolean variables for a nonterminal with k rules from k to k-1, with the last rule being the catchall case. This involves simplifying printing and evaluation for nonterminals with only one rule.

**Comment by eionblanc** [comment]
To allow functionality of evaluation until this issue is solved, I added assertions to the SMT output that for each nonterminal copy function, one of the boolean variables must be True (thus avoiding the catchall exception).

**Comment by eionblanc** [comment]
The solution to this issue requires fixing the .boolvars and .symbols attributes in ConstraintGrammar. The role of .boolvars in the evaluation and the expansion (pretty_smt_encoding) seems to need a True value for some boolean variable in each function dictating which production rule to "follow".

This will no longer be the case, since all boolean variables having False valuation will correspond to the last product rule being followed---how should .boolvars be restructured to reflect this? That is, since there is no boolean variable uniquely associated with the final production rule for each symbol, _where should we store the names of nonterminal copies corresponding to each last production rule_?

**Comment by muraliadithya** [comment]
That is exactly what I intended to do: have n-1 boolvars when there are n rules. But this becomes a little difficult when there is only one rule, because one needs to not declare any booleans or other functions for them, instead 'inline' them in the 'final evaluation' define-fun. 

As to where they will be stored, currently the mapping is not explicit as the rules are not named. The idea is there is, for every nonterminal N, a deterministically ordered rule list [R1, R2,...Rk]
And the boolvars are stored as a list [b1, b2,...bk] where the order corresponds to the order of rules. The nonterminal copies are stored as a list of lists, each inner list being copies, and the inner list being ordered corresponding to each rule. The only change that will happen is that the boolvars will now only have [b1, b2,...bk-1], and the code should reflect that while printing, evaluating etc. As before, this connection/correspondence will only be explained in the documentation but will not be enforced 'programmatically'.

I'm not particularly happy about this either. @eionblanc do you have an idea to do this better?

**Comment by eionblanc** [comment]
@muraliadithya I've added catch case storage in self.boolcatch; keys are the nonterminal copy string names while values are analogous to those for self.boolvars. I've accounted for this in the evaluation functions (no longer throws an exception) and the pretty printing.
